#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Embeds Tools/asn1/*.asn in Sources/RTLSDRDecoders/ATN/ATNModules.swift as Swift raw string literals.

usage: generate-asn1-modules.py [--check]     (--check fails if the checked-in file differs from what would be written)
"""
import glob
import os
import sys

here = os.path.dirname(os.path.abspath(__file__))
out_path = os.path.join(here, "..", "Sources", "RTLSDRDecoders", "ATN", "ATNModules.swift")


def render():
    lines = [
        "// SPDX-License-Identifier: GPL-2.0-or-later",
        "//",
        "// Generated by Tools/generate-asn1-modules.py from Tools/asn1/*.asn: do not edit. The modules are the Wireshark project's",
        "// copies (GPL-2.0-or-later) of ICAO Doc 9705's ASN.1 definitions; see Tools/asn1/README.md and PROVENANCE.md.",
        "import Foundation",
        "",
        "public enum ATNModules {",
    ]
    names = []
    for path in sorted(glob.glob(os.path.join(here, "asn1", "*.asn"))):
        name = os.path.basename(path)[:-4].replace("atn-", "").replace("-", "_")
        names.append(name)
        text = open(path, encoding="utf-8").read().replace("\r\n", "\n")
        assert '"""#' not in text
        lines.append(f"    public static let {name} = #\"\"\"")
        lines.append(text.rstrip("\n"))
        lines.append('"""#')
        lines.append("")
    lines.append("    /// Every module, in the order they are loaded.")
    lines.append("    public static let all = [" + ", ".join(names) + "]")
    lines.append("}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        current = open(out_path, encoding="utf-8").read() if os.path.exists(out_path) else ""
        sys.exit(0 if current == text else 1)
    open(out_path, "w", encoding="utf-8").write(text)
